import Img1 from '../../assets/img1.jpeg'
export const BlogPosts = [
    {
      id: 1,
      title: "Blog 1",
      author: 'John Doe',
      slug:"Blog-1",
      date: "September 14, 2022",
      content: "Lorem Ipsum is simply dummy text of the printing and typesetting industry...",
      contentDetails:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam et nisl sit amet justo malesuada tempor eget sed felis. Aenean porta nisi vel nibh ullamcorper, nec elementum velit scelerisque. Praesent condimentum at metus et dapibus. Fusce congue lorem vitae mauris congue, vitae imperdiet sem facilisis. Integer venenatis ornare varius. Etiam nisi nisl, tincidunt sit amet tristique nec, sodales mattis enim. In euismod vehicula luctus. Aenean efficitur arcu vehicula, condimentum nisl quis, mattis tellus. Cras ut eleifend metus, nec consequat velit. Suspendisse potenti. Donec consectetur justo velit, ut molestie massa volutpat non. Ut vehicula fermentum nunc, id euismod est pellentesque vel. Aliquam nec rhoncus tortor. Nunc porttitor viverra malesuada. Nullam tempor ullamcorper nunc id finibus. Vivamus varius, purus vel ullamcorper elementum, tellus est bibendum ligula, eget aliquam risus magna at lorem. In eleifend lacinia laoreet. Vestibulum faucibus erat a convallis vehicula. Quisque gravida eu sapien eget sodales. Aenean phar",
      image: Img1,
      likes:70,
    },
    {
        id: 2,
        title: "Blog 2",
        author: 'Jane Smith',
        slug:"Blog-2",
        date: "September 20, 2022",
        content: "Lorem Ipsum is simply dummy text of the printing and typesetting industry...",
        contentDetails:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam et nisl sit amet justo malesuada tempor eget sed felis. Aenean porta nisi vel nibh ullamcorper, nec elementum velit scelerisque. Praesent condimentum at metus et dapibus. Fusce congue lorem vitae mauris congue, vitae imperdiet sem facilisis. Integer venenatis ornare varius. Etiam nisi nisl, tincidunt sit amet tristique nec, sodales mattis enim. In euismod vehicula luctus. Aenean efficitur arcu vehicula, condimentum nisl quis, mattis tellus. Cras ut eleifend metus, nec consequat velit. Suspendisse potenti. Donec consectetur justo velit, ut molestie massa volutpat non. Ut vehicula fermentum nunc, id euismod est pellentesque vel. Aliquam nec rhoncus tortor. Nunc porttitor viverra malesuada. Nullam tempor ullamcorper nunc id finibus. Vivamus varius, purus vel ullamcorper elementum, tellus est bibendum ligula, eget aliquam risus magna at lorem. In eleifend lacinia laoreet. Vestibulum faucibus erat a convallis vehicula. Quisque gravida eu sapien eget sodales. Aenean phar",
        image: Img1,
        likes:70,
      },
      {
        id: 3,
        title: "Blog 3",
        author: 'John Doe',
        slug:"Blog-3",
        date: "September 30, 2022",
        content: "Lorem Ipsum is simply dummy text of the printing and typesetting industry...",
        contentDetails:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam et nisl sit amet justo malesuada tempor eget sed felis. Aenean porta nisi vel nibh ullamcorper, nec elementum velit scelerisque. Praesent condimentum at metus et dapibus. Fusce congue lorem vitae mauris congue, vitae imperdiet sem facilisis. Integer venenatis ornare varius. Etiam nisi nisl, tincidunt sit amet tristique nec, sodales mattis enim. In euismod vehicula luctus. Aenean efficitur arcu vehicula, condimentum nisl quis, mattis tellus. Cras ut eleifend metus, nec consequat velit. Suspendisse potenti. Donec consectetur justo velit, ut molestie massa volutpat non. Ut vehicula fermentum nunc, id euismod est pellentesque vel. Aliquam nec rhoncus tortor. Nunc porttitor viverra malesuada. Nullam tempor ullamcorper nunc id finibus. Vivamus varius, purus vel ullamcorper elementum, tellus est bibendum ligula, eget aliquam risus magna at lorem. In eleifend lacinia laoreet. Vestibulum faucibus erat a convallis vehicula. Quisque gravida eu sapien eget sodales. Aenean phar",
        image: Img1,
        likes:70,
      },
      {
        id: 4,
        title: "Blog 4",
        author: 'John Doe',
        slug:"Blog-4",
        date: "September 14, 2022",
        content: "Lorem Ipsum is simply dummy text of the printing and typesetting industry...",
        contentDetails:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam et nisl sit amet justo malesuada tempor eget sed felis. Aenean porta nisi vel nibh ullamcorper, nec elementum velit scelerisque. Praesent condimentum at metus et dapibus. Fusce congue lorem vitae mauris congue, vitae imperdiet sem facilisis. Integer venenatis ornare varius. Etiam nisi nisl, tincidunt sit amet tristique nec, sodales mattis enim. In euismod vehicula luctus. Aenean efficitur arcu vehicula, condimentum nisl quis, mattis tellus. Cras ut eleifend metus, nec consequat velit. Suspendisse potenti. Donec consectetur justo velit, ut molestie massa volutpat non. Ut vehicula fermentum nunc, id euismod est pellentesque vel. Aliquam nec rhoncus tortor. Nunc porttitor viverra malesuada. Nullam tempor ullamcorper nunc id finibus. Vivamus varius, purus vel ullamcorper elementum, tellus est bibendum ligula, eget aliquam risus magna at lorem. In eleifend lacinia laoreet. Vestibulum faucibus erat a convallis vehicula. Quisque gravida eu sapien eget sodales. Aenean phar",
        image: Img1,
        likes:70,
      },
      {
        id: 5,
        title: "Blog 5",
        author: 'John Doe',
        slug:"Blog-5",
        date: "September 24, 2022",
        content: "Lorem Ipsum is simply dummy text of the printing and typesetting industry...",
        contentDetails:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam et nisl sit amet justo malesuada tempor eget sed felis. Aenean porta nisi vel nibh ullamcorper, nec elementum velit scelerisque. Praesent condimentum at metus et dapibus. Fusce congue lorem vitae mauris congue, vitae imperdiet sem facilisis. Integer venenatis ornare varius. Etiam nisi nisl, tincidunt sit amet tristique nec, sodales mattis enim. In euismod vehicula luctus. Aenean efficitur arcu vehicula, condimentum nisl quis, mattis tellus. Cras ut eleifend metus, nec consequat velit. Suspendisse potenti. Donec consectetur justo velit, ut molestie massa volutpat non. Ut vehicula fermentum nunc, id euismod est pellentesque vel. Aliquam nec rhoncus tortor. Nunc porttitor viverra malesuada. Nullam tempor ullamcorper nunc id finibus. Vivamus varius, purus vel ullamcorper elementum, tellus est bibendum ligula, eget aliquam risus magna at lorem. In eleifend lacinia laoreet. Vestibulum faucibus erat a convallis vehicula. Quisque gravida eu sapien eget sodales. Aenean phar",
        image: Img1,
        likes:70,
      },
      {
        id: 6,
        title: "Blog 6",
        author: 'John Doe',
        slug:"Blog-6",
        date: "September 03, 2022",
        content: "Lorem Ipsum is simply dummy text of the printing and typesetting industry...",
        contentDetails:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam et nisl sit amet justo malesuada tempor eget sed felis. Aenean porta nisi vel nibh ullamcorper, nec elementum velit scelerisque. Praesent condimentum at metus et dapibus. Fusce congue lorem vitae mauris congue, vitae imperdiet sem facilisis. Integer venenatis ornare varius. Etiam nisi nisl, tincidunt sit amet tristique nec, sodales mattis enim. In euismod vehicula luctus. Aenean efficitur arcu vehicula, condimentum nisl quis, mattis tellus. Cras ut eleifend metus, nec consequat velit. Suspendisse potenti. Donec consectetur justo velit, ut molestie massa volutpat non. Ut vehicula fermentum nunc, id euismod est pellentesque vel. Aliquam nec rhoncus tortor. Nunc porttitor viverra malesuada. Nullam tempor ullamcorper nunc id finibus. Vivamus varius, purus vel ullamcorper elementum, tellus est bibendum ligula, eget aliquam risus magna at lorem. In eleifend lacinia laoreet. Vestibulum faucibus erat a convallis vehicula. Quisque gravida eu sapien eget sodales. Aenean phar",
        image: Img1,
        likes:70,
      }
];

